apiVersion: apps/v1 
kind: Deployment
metadata:
  name: "$Username-$random-suchja-wine"
  labels:
    app: "$Username-$random-suchja-wine"
    client: "$Username-$random"
spec:
  selector:
    matchLabels:
      app: "$Username-$random-suchja-wine"
      client: "$Username-$random"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "$Username-$random-suchja-wine"
        client: "$Username-$random"
    spec:
      containers:
      - image: launchthatbrand/suchja-wine:1.0.0
        name: "$Username-$random-suchja-wine"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "${MEM}Gi"
            cpu: "${CPU}m"
        env:
        - name: VNC_SERVER
          value: "yes"
        - name: USER_NAME
          value: $Username
        - name: USER_PASSWD
          value: $Password
        volumeMounts:
        - name: $Username-$random-suchja-wine
          mountPath: /home/$Username
          
      - image: launchthatbrand/suchja-x11server:1.0.0
        name: "$Username-$random-suchja-x11server"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "${MEM}Gi"
            cpu: "${CPU}m"
        volumeMounts:
        - name: $Username-$random-suchja-wine
          mountPath: /home/$Username
      volumes:
      - name: $Username-$random-suchja-wine
        persistentVolumeClaim:
          claimName: $Username-$random-suchja-wine
---
apiVersion: v1
kind: Service
metadata:
  name: "$Username-$random-suchja-wine"
  labels:
    app: "$Username-$random-suchja-wine"
    client: "$Username-$random"
spec:
  ports:
  - port: 5900
    protocol: TCP
    targetPort: 5900
  selector:
    app: "$Username-$random-suchja-wine"
    client: "$Username-$random"
  type: $type
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "$Username-$random-suchja-wine"
  labels:
    app: "$Username-$random-suchja-wine"
    client: "$Username-$random"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
